export const palette = {
  primary: '#eff2f5',
  secondary: '#FFC300',
  border: '#6161612e',
  greenHover: '#4edecb',
  green: '#28d1c1',
  dark: '#000',
  white: '#fff',
  yellow: '#ffd92c',
  pink: '#ff9ab7',
  orange: '#FF5733',
  darkGray: '#3e3e3e',
  gray: '#bdc3c7',
  defaultgray: '#fafafa',
  mediumGray: 'gray',
  ultraLightGray: '#efefef',
  lightGray: '#cecece',
  mediumLightGray: '#a09d9d',
  blackGray: '#3a3a3a',
  thinGray: '#ededed',
  whiteGray: '#fbfbfb',
  lightBlue: '#f0fbff',
  mediumBlue: '#5bc0de',
  red: '#f5222d',
  blue: '#6fb5de',
  success: '#27AE60',
  failure: '#C70039',
}
